### ISSUE TITLE
Issue running the GWT-D3-DEMO

### ISSUE THREAD

**Issue by soodrah** [gwtd3/gwt-d3#128]
hi 
I am trying to run the GWT-D3-Demo from within my eclipse but keep hitting this error. I have many other maven gwt demos working of other projects but cant get this one to work. Can you shed some light. Also I had problem finding gwt-dev-2.7.0.jar from maven, it would only recognize gwt-dev-2.8.jar, whats up with that.. here is my exception
Starting Jetty on port 8888
   [WARN] Failed startup of context c.g.g.d.s.j.WebAppContextWithReload{/,file:/Users/rahulsood/Data/sandbox/gwt-d3-master/gwt-d3-demo/src/main/webapp/},/Users/rahulsood/Data/sandbox/gwt-d3-master/gwt-d3-demo/src/main/webapp
java.io.EOFException
	at java.util.zip.ZipInputStream.readFully(ZipInputStream.java:405)
	at java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:321)
	at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:122)
	at java.util.jar.JarInputStream.<init>(JarInputStream.java:83)
	at java.util.jar.JarInputStream.<init>(JarInputStream.java:62)
	at org.eclipse.jetty.webapp.JarScanner.matched(JarScanner.java:155)
	at org.eclipse.jetty.util.PatternMatcher.matchPatterns(PatternMatcher.java:100)
	at org.eclipse.jetty.util.PatternMatcher.match(PatternMatcher.java:82)
	at org.eclipse.jetty.webapp.JarScanner.scan(JarScanner.java:84)
	at org.eclipse.jetty.webapp.MetaInfConfiguration.preConfigure(MetaInfConfiguration.java:84)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:457)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:493)
	at com.google.gwt.dev.shell.jetty.JettyLauncher$WebAppContextWithReload.doStart(JettyLauncher.java:541)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.handler.RequestLogHandler.doStart(RequestLogHandler.java:162)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at com.google.gwt.dev.shell.jetty.JettyLauncher.start(JettyLauncher.java:740)
	at com.google.gwt.dev.DevMode.doStartUpServer(DevMode.java:632)
	at com.google.gwt.dev.DevModeBase.startUp(DevModeBase.java:992)
	at com.google.gwt.dev.DevModeBase.run(DevModeBase.java:775)
	at com.google.gwt.dev.DevMode.main(DevMode.java:428)
[ERROR] 503 - GET /D3Demo.html?gwt.codesvr=127.0.0.1:9997 (127.0.0.1) 1298 bytes

Here are my set up params Program arguements
-war /Users/rahulsood/Data/sandbox/gwt-d3-master/gwt-d3-demo/src/main/webapp -nosuperDevMode -remoteUI "${gwt_remote_ui_server_port}:${unique_id}" -logLevel INFO -codeServerPort 9997 -port 8888 com.github.gwtd3.demo.D3Demo

Main class is 
DevMode

**Comment by anthonime** [comment]
have you tried using superdevmode ? remove the "-nosuperDevMode" argument
